### ISSUE TITLE
When using template to list over array, an additional row is created with the variable names

### ISSUE THREAD

**Issue by boardy** [webdevelopers-eu/jquery-lazy-template#1]
There seems to a problem when using a template to loop over and display an array, an additional row is created that includes the variable names but the row shouldn't be there at all. For example, the output I am getting is as follows:

First Name | Last Name
-- | --
FName1 | LName1
FName2 | LName2
FName3 | LName3
${FirstName} | ${LastName}

The following javascript is used:

```
$('[template="names_template"]').template(
        [
            {
                "FirstName": "FName1",
                "LastName": "LName1"
            },
            {
                "FirstName": "FName2",
                "LastName": "LName2"
            },
            {
                "FirstName": "FName3",
                "LastName": "LName3"
            }
        ]
    );
```

And the following HTML

```
<table class="table table-bordered table-hover table-striped table-condensed">
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                </tr>
                <tr template="names_template">
                    <td z-var="FirstName .">${FirstName}</td>
                    <td z-var="LastName .">${LastName}</td>
                </tr>
            </table>
```

Thanks

**Comment by webdevelopers-eu** [comment]
Hello Chris,

that is on purpose. The template application is non-destructive so
templates are not removed. You can run the code again with different data
and it will get applied again thanks to preserved template tags...

There is a simple CSS trick to hide it. You were supposed to include also
template.css that will hide all elements having "template" attribute:

https://github.com/webdevelopers-eu/jquery-lazy-template/blob/master/template.css

When you are selecting elements by jQuery you should exclude all elements
with "template" attribute. E.g. in your example to select all rows would be
$('tr:not([template])') because that template row will be always present
but not visible (hidden by CSS above).

Did I explained it? Does it limit you in some way?

--daniel

**Comment by webdevelopers-eu** [comment]
BTW you don't need to use `${FirstName}` in the text contents if you want to insert only that variable (`<td z-var="LastName ."></td>`). It is useful if you want to insert variables into other text (e.g. ` <td z-var="FirstName .">My name is ${FirstName}</td>`)

```
<table class="table table-bordered table-hover table-striped table-condensed">
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                </tr>
                <tr template="names_template">
                    <td z-var="FirstName ."></td>
                    <td z-var="LastName ."></td>
                </tr>
            </table>
```

**Comment by boardy** [comment]
@webdevelopers-eu Thanks for the quick response. 

Sorry, I missed the point of the css file (that's what I get for trying to code after 9pm), that's perfect. 

Great library 👍

**Comment by webdevelopers-eu** [comment]
Thanks! :-)
