### ISSUE TITLE
[Possible Feature] Option to destruct before loading template

### ISSUE THREAD

**Issue by boardy** [webdevelopers-eu/jquery-lazy-template#3]
This may be a little outside the scope of your project as the idea is to be non-destructive, however I had a user case where I need to implement this. 

Basically, what I was doing was loading data from a database into a template, all of the data is returned from the DB (its not massive but too big to display on the page neatly) so was looking at paging the data that is returned from the DB. I was doing this by loading the template, then when the next/previous page is clicked, it would get the next/previous set of data but as intended by this project, added the data to what already existed, therefore wanted to remove what was loaded into the template, then re-populate with the new dataset. 

I've implemented this myself but was wondering whether this is something you would like to add to this project, its not a problem, if you feel this is out of scope of this project and not want to include it, but if so, happy to do a pull request. 

I'm not a javascript/jquery expert by any means and you may have a better way of doing what I've done, so more than happy for you to offer any suggestions. 

I've added an extra parameter to $.fn.template called destructFirst. It defaults to false, but if its true, it removes any element where template-clone attribute equals the template name. 

Below is the code snippet of what I've done

```
var destructFirst = (typeof destructFirst !== typeof undefined) ? destructFirst : false;
    if (destructFirst)
    {
        var templateName = $(this).attr("template");
        if (typeof templateName !== typeof undefined)
        {
            $(document).find("[template-clone='"+templateName+"']").remove();
        }
    }
```

The above code is done at the top of the template function call. 

Thanks

Chris

**Comment by webdevelopers-eu** [comment]
Hello boardy,

I believe that this use case scenario is already covered. Check this out and let me know if it is applicable to your case:

[CodePen Paging Example](https://codepen.io/webdevelopers/pen/XePggZ?editors=1010)

When re-applying the dataset with subarrays I am already removing cloned templates automatically. I don't do that in case that you call .template() separately for each displayed row because it is difficult to know what should be removed automatically... But when you take advantage of an array support then it is clear that .template() should clean up all nested "template-clone" elements and it does so.

Thanks for feedback,

Daniel

**Comment by webdevelopers-eu** [comment]
I am closing this as I think the suggested feature is already implemented. Feel free to fill out new request if I missed something...
