### ISSUE TITLE
Issue with inner html when using placeholders

### ISSUE THREAD

**Issue by Pimentero** [webdevelopers-eu/jquery-lazy-template#6]
Hi!

I think it can be an issue:

When using `z-var="var text"` with placeholder like this `<div z-var="var text">Just text: ${var}</div>` - it renders as text, as expected. But when there are tags inside div, like this `<div z-var="var text"><img src="..."> ${var}</div>` - img is removed.

Here is an example: https://codepen.io/pimentero/pen/abROrMd

**Comment by webdevelopers-eu** [comment]
Hi,

no, it is by design. Text content is expected to be alone in the element.
Just wrap the text with the variable.

<div id="app">
  <div z-var="hello text">text: ${hello}</div>
  <div><a href="https://google.com">link</a>: <span z-var="hello
text">${hello}</span></div>
</div>

If "${hello}" is the only text content then you can leave it out completely:

<div id="app">
  <div z-var="hello text">text: ${hello}</div>
  <div><a href="https://google.com">link</a>: <span z-var="hello
text"></span></div>
</div>

Cheers,

Daniel

**Comment by webdevelopers-eu** [comment]
Hi,

no, it is by design. Text content is expected to be alone in the element. Just wrap the text with the variable.

```
<div id="app">
  <div z-var="hello text">text: ${hello}</div>
  <div><a href="https://google.com/">link</a>: <span z-var="hello text">${hello}</span></div>
</div>

```
If "${hello}" is the only text content then you can leave it out completely:

```
<div id="app">
  <div z-var="hello text">text: ${hello}</div>
  <div><a href="https://google.com/">link</a>: <span z-var="hello text"></span></div>
</div>
```

Cheers,

Daniel
